apiVersion: v2
appVersion: 1.3.7
description: A chart to deploy code servers for your Dagster deployment.
icon: https://elementl.com/icons/social/dagster.jpg
keywords:
- analytics
- data-orchestrator
- data-pipelines
- etl
- workflow
kubeVersion: '>= 1.18.0-0'
maintainers:
- email: support@elementl.com
  name: Elementl
  url: https://elementl.com
name: dagster-user-deployments
sources:
- https://github.com/dagster-io/dagster/tree/master/helm/dagster/charts/dagster-user-deployments
type: application
version: 1.3.7
