dagit:
  service:
    type: NodePort
    nodePort: 30003
dagster-user-deployments:
  deployments:
    - name: "financial"
      image:
        repository: "docker.io/jazzdung/dagster-financial"
        tag: "sha-ed841ac"
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/financial/dagster/financial/__init__.py"
        - "--working-directory"
        - "/financial/dagster"
      port: 3030
      volumes:
        - name: secret-dbt
          secret:
            secretName: secret-dbt
        - name: secret-dagster
          secret:
            secretName: secret-dagster
            # - name: task-pv-storage
            #   persistentVolumeClaim:
            #     claimName: user-model-claim
      volumeMounts:
        - name: secret-dbt
          mountPath: /secret-dbt
          readOnly: true
        - name: secret-dagster
          mountPath: /financial/dagster/financial/secret
          readOnly: true
          # - name: task-pv-storage
          #   mountPath: "/financial/dbt/models/user"
postgresql:
  enabled: false
  postgresqlHost: timescaledb.fdp.svc.cluster.local
  postgresqlUsername: dagster
  postgresqlPassword: dagster
  postgresqlDatabase: db_dagster
