# dagit:
#   service:
#     type: NodePort

dagster-user-deployments:
  enableSubchart: true
  deployments:
    - name: "test"
      image:
        # When a tag is not supplied, it will default as the Helm chart version.
        repository: "docker.io/jazzdung/dagster-financial"
        tag: 0.1
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/financial/financial/financial/__init__.py"
        - "--working-directory"
        - "/financial/financial"
      port: 3030

# postgresql:
#   persistence:
#     size: 1Gi

postgresql:
  enabled: false
  postgresqlHost: timescaledb.fdp.svc.cluster.local
  postgresqlUsername: dagster
  postgresqlPassword: dagster
  postgresqlDatabase: db_dagster
