# dagit:
#   service:
#     type: NodePort

dagster-user-deployments:
  enableSubchart: true

# postgresql:
#   persistence:
#     size: 1Gi

postgresql:
  enabled: false
  postgresqlHost: timescaledb.fdp.svc.cluster.local
  postgresqlUsername: dagster
  postgresqlPassword: dagster
  postgresqlDatabase: db_dagster