service:
  type: NodePort
  nodePort:
    http: 30007
postgresql:
  enabled: false
supersetNode:
  replicaCount: 1
  connections:
    db_host: 'timescaledb.fdp.svc.cluster.local'
    db_port: "5432"
    db_user: superset
    db_pass: superset
    db_name: superset
  resources:
    limits:
      cpu: 2000m
      memory: 2560Mi
    requests:
      cpu: 200m
      memory: 256Mi
supersetCeleryBeat:
  enabled: true
image:
  repository: perceptiveperceval/thesis
  tag: "sha-5244dff"
configOverrides:
  override_file: |
      SAVE_QUERY_SCHEMA = "financial_query"
      AVAILABLE_SCHEMAS = ["financial_clean", "financial_user"]
      SAVE_QUERY_TABLE = "query"
  registration: |
      AUTH_TYPE = AUTH_DB

      AUTH_ROLE_ADMIN = 'Admin'

      AUTH_ROLE_PUBLIC = 'User'


      AUTH_USER_REGISTRATION = True

      AUTH_USER_REGISTRATION_ROLE = "Public"


      RECAPTCHA_PUBLIC_KEY = '6LestignAAAAAP09-EZCr5RykOBJ1hiZmCXHy8AP'
      RECAPTCHA_PRIVATE_KEY = '6LestignAAAAAHTd_vToS55axYh0Lx07qQIoWIOd'

      MAIL_SERVER = 'smtp.gmail.com'
      MAIL_USE_TLS = True
      MAIL_USERNAME = 'catvusuperset@gmail.com'
      MAIL_PASSWORD = 'iphqwawmeqrtcyfv'
      MAIL_DEFAULT_SENDER = 'catvusuperset@gmail.com'
      MAIL_PORT = 587
