service:
  type: NodePort
  nodePort:
    http: 30007

postgresql:
  enabled: false

supersetNode:
  replicaCount: 1
  connections:
    db_host: 'timescaledb.fdp.svc.cluster.local'
    db_port: "5432"
    db_user: superset
    db_pass: superset
    db_name: superset