grafana:
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30004
  grafana.ini:
    smtp: 
      enabled: true
      host: smtp.gmail.com:465
      user: viphungquoc@gmail.com
      password: xsqkhnwtywwuinpj
      from_address: viphungquoc@gmail.com