apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-dagit-env
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ include "dagster.shared_env" . | nindent 2 }}
  # This is a list by default, but for backcompat it can be a map. If it's a list, the env is applied directly
  # to the container.
  {{- if and (.Values.dagit.env) (kindIs "map" .Values.dagit.env) }}
  {{- range $name, $value := .Values.dagit.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
