{{- $data := dict "Values" .Values "Release" .Release "Chart" .Chart "Template" .Template -}}
{{- include "deployment-dagit" $data -}}

{{- if .Values.dagit.enableReadOnly -}}
---
{{$data := dict "Values" .Values "Release" .Release "Chart" .Chart "Template" .Template "dagitReadOnly" true}}
{{- include "deployment-dagit" $data -}}
{{- end -}}
