{{- if (and .Values.migrate .Values.migrate.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dagster.dagit.migrate" . | quote }}
spec:
  template:
    metadata:
      name: {{ include "dagster.dagit.migrate" . | quote }}
    spec:
      imagePullSecrets: {{ .Values.imagePullSecrets | toYaml | nindent 8 }}
      serviceAccountName: {{ include "dagster.serviceAccountName" . }}
      securityContext: {{ .Values.dagit.podSecurityContext | toYaml | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: dagster-instance-migrate
          securityContext: {{ .Values.dagit.securityContext | toYaml | nindent 12 }}
          imagePullPolicy: {{ .Values.dagit.image.pullPolicy }}
          image: {{ include "dagster.dagsterImage.name" (list $ .Values.dagit.image) | quote }}
          command: ["dagster"]
          args: ["instance", "migrate"]
          env:
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dagster.postgresql.secretName" . | quote }}
                  key: postgresql-password
          envFrom:
            - configMapRef:
                name: {{ template "dagster.fullname" . }}-dagit-env
            {{- range $envConfigMap := .Values.dagit.envConfigMaps }}
            - configMapRef: {{- $envConfigMap | toYaml | nindent 16 }}
            {{- end }}
            {{- range $envSecret := .Values.dagit.envSecrets }}
            - secretRef: {{- $envSecret | toYaml | nindent 16 }}
            {{- end }}
            {{- if eq $.Values.runLauncher.type "CeleryK8sRunLauncher" }}
            - secretRef:
                name: {{ $.Values.global.celeryConfigSecretName }}
            {{- end }}
          volumeMounts:
            - name: dagster-instance
              mountPath: "{{ .Values.global.dagsterHome }}/dagster.yaml"
              subPath: dagster.yaml
          resources: {{ .Values.dagit.resources | toYaml | nindent 12 }}
      volumes:
        - name: dagster-instance
          configMap:
            name: {{ template "dagster.fullname" . }}-instance
      nodeSelector: {{ .Values.dagit.nodeSelector | toYaml | nindent 8 }}
      affinity: {{ .Values.dagit.affinity | toYaml | nindent 8 }}
      tolerations: {{ .Values.dagit.tolerations | toYaml | nindent 8 }}
{{- end }}
