apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timescaledb
  namespace: argocd
spec:
  project: default
  source:
#    chart: timescaledb-single
    repoURL: https://github.com/vietcheems/fdp-helm-chart
    targetRevision: HEAD
    path: guestbook
    helm:
      releaseName: timescaledb
      valueFiles:
      - myvalues.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fdp