name: Update User Code Image

on:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: TAG=$(echo ${{ github.event.client_payload.tag }} | cut -d ':' -f 2)  yq eval ".dagster-user-deployments.deployments[0].image.tag = env(TAG)" -i dagster/myvalues.yaml
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update user code image version
